name: Cl
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@vl
    - uses: ruby/setup-ruby@vl
    with:
      ruby-version: 2.6
      bundler-cache: true
  - name: Build and run tests
  env:
   SECRETS_URL: ${{ secrets.SECRETS_URL }}
   run: |
     bundle exec fastlane build and run test
