name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    env:
    SECRETS_URL: ${{ secrets.SECRETS_URL }}
      run: bundle exec fastlane
